version: '2.3'
services:
  tests:
    image: buildkite/plugin-tester:latest@sha256:a784b49bb241291feb47b578a2cb58938d3565dff5b0f6d9bf627036cbd7f419
    volumes:
      - ".:/plugin:ro"
  appenv:
    build:
      context: ghapp
      dockerfile: Dockerfile
  ghapp:
    extends: appenv
    environment:
      - CI
      - BUILDKITE
      - BUILDKITE_LABEL
      - BUILDKITE_BRANCH
      - BUILDKITE_COMMIT
      - BUILDKITE_REPO

      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL

      - BUILDKITE_JOB_ID
      - BUILDKITE_COMMAND
      - BUILDKITE_TIMEOUT
      - BUILDKITE_COMMAND_EXIT_STATUS

      - GITHUB_APP_AUTH_ID
      - GITHUB_APP_AUTH_KEY
    entrypoint: ghapp
  ghapp-tests:
    extends: appenv
    working_dir: /ghapp
    entrypoint: python3 setup.py test --addopts -v
